const PATH = '/img/optimized/'
//image orientation
const LANDSCAPE = 'landscape';
//use for orientation and for category
const PORTRAIT = 'portrait'

//CATEGORIES
const LIVE = 'live'
const LIFESTYLE = 'lifestyle'

export const photos = [
    {
      src: `${PATH}FD1U7915.jpg`,
      width:  929.9,
      height: 620,
      key: 0,
      width2: 466,
      height2: 310.7,
      alt: "Warmly colored photo of <BAND NAME HERE> performing live",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIVE]
    },
    {
      src: `${PATH}0X9A9184.jpg`,
      width: 3,
      height: 4,
      key: 1,
      width2: 466,
      height2: 621.3,
      alt: "Birds eye view, violet-hued photograph of brightly colored buildings by a forested river",
      useInHeroCarousel: true,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}7H2A8660 2.jpg`,
      width:  929.9,
      height: 620,
      key: 2,
      width2: 466,
      height2: 310.7,
      alt: "Live band performance. Performer laying on the ground and causing sparks with a saw",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIVE]
    },
    {
      src: `${PATH}_F0A5112.jpg`,
      width: 3,
      height: 4,
      key: 3,
      width2: 466,
      height2: 621.3,
      alt: "Black and white photograph of snowcapped woods surrounding a waterfall and river",
      useInHeroCarousel: true,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}7H2A1896.jpg`,
      width: 3,
      height: 4,
      key: 4,
      width2: 466,
      height2: 621.3,
      alt: "Black and white photograph of a lone, winter dormant tree against an overcast sky ",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}0X9A9188.jpg`,
      width: 3,
      height: 4,
      key: 5,
      width2: 466,
      height2: 621.3,
      alt: "Birds eye view photograph of a beach with a small, lone figure walking along the coast. ",
      useInHeroCarousel: true,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}1S6A3166.jpg`,
      width: 3,
      height: 4,
      key: 6,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: true,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}FD1U8022.jpg`,//source.unsplash.com/I1ASdgphUH4/800x599,
      width: 3,
      height: 4,
      key: 7,
      width2: 466,
      height2: 621.3,
      alt:  "Live performance of <BAND NAME HERE> with smoke and purple hue",
      useInHeroCarousel: true,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIVE]
    },
    {
      src: `${PATH}FD1U6972-3.jpg`,
      width: 3,
      height: 4,
      key: 8,
      width2: 466,
      height2: 621.3,
      alt: "Color photo of man walking in downtown Huntsville, AL across wet pavement crosswalk",
      useInHeroCarousel: true,
      orientation: PORTRAIT,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}0X9A8563.jpg`,
      width: 3,
      height: 4,
      key: 9,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: true,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A0027.jpg`,
      width: 3,
      height: 4,
      key: 10,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: true,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}FD1U7367.jpg`,
      width:  929.9,
      height: 620,
      key: 11,
      width2: 466,
      height2: 310.7,
      alt: "Live performance of Comeback Kid from FurnaceFest 2021 in Birmingham, AL",
      useInHeroCarousel: true,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIVE]
    },
    {
      src: `${PATH}FWDGUY.jpg`,
      width:  929.9,
      height: 620,
      key: 12,
      width2: 466,
      height2: 310.7,
      alt: "Photograph of a sharply dressed man with cheap sunglasses doing a stoppie (front wheelie) on a bicycle in front of a shop in downtown Huntsville, AL ",
      useInHeroCarousel: true,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U7554.jpg`,
      width:  929.9,
      height: 620,
      key: 13,
      width2: 466,
      height2: 310.7,
      alt: "Live performance of Darkest Hour from FurnaceFest 2021 in Birmingham, AL",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIVE]
    },
    {
      src: `${PATH}0X9A8593.jpg`,
      width:  929.9,
      height: 620,
      key: 14,
      width2: 466,
      height2: 310.7,
      alt: "Black and white photo of public demonstration in downtown Huntsville, AL",
      useInHeroCarousel: true,
      orientation: LANDSCAPE,
      homepage: true,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}000017320007.jpg`,
      width: 3,
      height: 4,
      key: 15,
      width2: 466,
      height2: 621.3,
      alt: "Woman with painted face and cowgirl hat.",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}000019150020.jpg`,
      width: 3,
      height: 4,
      key: 16,
      width2: 466,
      height2: 621.3,
      alt: "Color portrait of some nerd",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}000022210024.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Whippet man with his can and minis",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}000026150018.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 310.7,
      alt: "Man posing in front of a graveyard in Huntsville, AL",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}000026150019.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Man sparking up",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}000026150033.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Utah Jazz",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U0167.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Knocked Loose in Huntsville, AL",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}FD1U0287.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Knocked Loose performing in downtown Huntsville, AL",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}FD1U0506.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Gojira live in Huntsville, AL",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}FD1U0656.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Acacia Strain? in Huntsville, AL. ",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}FD1U1262.jpg`,
      width:  929.9,
      height: 620,
      key: 17,
      width2:  929.9,
      height2: 620,
      alt: "Dilapidated boat by a chain link fence.",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U8614.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 310.7,
      alt: "DO SOMETHING GREAT",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U8808.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 310.7,
      alt: "Black and white photograph of a lake",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}0X9A0125.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A0150.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait aga",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A1771 2.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A4309.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 310.7,
      alt: "Cancerslug on couch",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}0X9A4334.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "UNHOLY CANCERSLUG",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}0X9A7157.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A8456.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A9371.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Black and white pizza portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}0X9A9487.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Drummer in fishnets",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}0X9A9611.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Mic Hole",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    },
    {
      src: `${PATH}1S6A2069 3.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Looking out of a window",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}1S6A5691.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Color Portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}7H2A7447.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Killough's tongue",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}7H2A8348.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}7H2A8449.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "black and white portrait. Jugalette?",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}7H2A8589 2.JPG`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "there's a thick tophat",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}000000060007.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "black and white portrait",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [PORTRAIT]
    },
    {
      src: `${PATH}FD1U6892-2.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 310.7,
      alt: "goody vault masked up",
      useInHeroCarousel: false,
      orientation: LANDSCAPE,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U7445.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "pumped",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIFESTYLE]
    },
    {
      src: `${PATH}FD1U7956.jpg`,
      width: 3,
      height: 4,
      key: 17,
      width2: 466,
      height2: 621.3,
      alt: "Furnace Fest Birmingham, AL",
      useInHeroCarousel: false,
      orientation: PORTRAIT,
      homepage: false,
      categories: [LIVE]
    }, 
  ];


export const getImagesForCarouselBasedOnScreenSize = (photos, screenOrientation) => {
  return photos.filter(photo => photo.orientation == screenOrientation && photo.useInHeroCarousel === true);
}

export const getHomePageImages = (photos, onHomepage) => {
  //return onHomepage ?  Object.values(photos).filter(photo => photo.homepage === true) : photos;
  return photos;
}

export const getListOfImageSources = (photos) => {
  return photos.map(photo => photo.src);
}